feature(ui-ux): added parser for transferDomain txn type
BirthdayResearch/defiscan.live pull request #1797
Opened 2023-05-25 05:37 UTC by fullstackninja864

#### What this PR does / why we need it:
In this PR we have added parser for TransferDomain txn type and updated `defi-blockchain` docker image to support evm release and enabled evm support for playground
#### Which issue(s) does this PR fixes?:

Fixes #

#### Sample Links & Screenshots:

Link:

<details>
<summary>Desktop Screenshot</summary>

</details>
<details>
<summary>Mobile Screenshot</summary>

</details>

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on multiple web browsers
- [ ] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [ ] No console errors
- [ ] Unit tests\*
- [ ] Added e2e tests\*

2023-05-26 02:30 UTC, pierregee requested changes
Can we add tests under `cypress/e2e/pages/transactions/DfTx`?

2023-05-26 03:47 UTC, fullstackninja864 commented
> Can we add tests under cypress/e2e/pages/transactions/DfTx?
@pierregee 
We can but currently we don't have mainnet txn for evmin and evmout, Lets wait for main net txn

2023-08-02 06:11 UTC, lykalabrada reviewed
LGTM!

2023-08-02 06:25 UTC, lykalabrada approved these changes

2023-08-02 23:41 UTC, pierregee approved these changes

2023-08-02 23:42 UTC, merged